////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

:log4j-url: {logging-services-url}/log4j/2.x
:log4j-api-url: {log4j-url}/manual/api-separation.html

= Log4j Kotlin API

{project-name} provides a Kotlin-friendly interface to log against {log4j-api-url}[the Log4j API].
The minimum requirements are Java `{java-target-version}` and Kotlin `{kotlin-version}`.

[IMPORTANT]
====
This is just a logging API.
Your application still needs to have a logging backend (e.g., {log4j-url}[Log4j]) configured.
====

[#dependencies]
== Dependencies

You need to have the `org.apache.logging.log4j:log4j-api-kotlin` dependency in your classpath:

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-api-kotlin</artifactId>
  <version>{project-version}</version>
</dependency>
----

Java module name and OSGi `Bundle-SymbolicName` are set to `org.apache.logging.log4j.api.kotlin`.

[#create-loggers]
== Creating loggers

A `Logger` is the primary interface that users interact with Log4j Kotlin.
You can create ``Logger``s particularly in two ways:

* <<class-loggers,Associate them with the class>> (*Recommended!*)
* <<instance-loggers,Associate them with the instance>>

[#class-loggers]
=== [[usage]] Creating class loggers

For most applications, we recommend you to create *a single logger instance per class definition* – not <<instance-loggers,per class instance>>!
This not only avoids creating an extra logger field for each instance, its access pattern transparently communicates the implementation: the `Logger` is statically bound to the class definition.
You can create class loggers in one of following ways:

[#create-companion-logger]
==== Creating a logger in the companion object

This is the traditional approach to create class loggers.
It also happens to be the most efficient one, since the logger lookup is performed once and its result is stored in the companion object shared by all instances of the class.

[source,kotlin]
----
import org.apache.logging.log4j.kotlin.logger

class DbTableService {

  companion object {

    private val LOGGER = logger() // <1>

  }

  fun truncateTable(tableName: String) {
    LOGGER.warn { "truncating table `${tableName}`" }
    db.truncate(tableName)
  }

}
----
<1> Create a `Logger` associated with the static class definition that all instances of the class share

[#extend-companion]
==== Extending companion object from `Logging`

`Logging` interface contains a `logger` getter that you can use by extending the companion object from the `Logging` class:

[source,kotlin]
----
import org.apache.logging.log4j.kotlin.Logging

class DbTableService {

  companion object: Logging // <1>

  fun truncateTable(tableName: String) {
    logger.warn { "truncating table `${tableName}`" }
    db.truncate(tableName)
  }

}
----
<1> Extending the companion object from `Logging` effectively creates a single `Logger` instance
. Assigned to the `logger` field
. Associated with the static class definition that all instances of the class share

[NOTE]
====
This getter-based approach incurs an extra overhead (compared to <<create-companion-logger>>) due to the logger lookup involved at runtime.
====

[#instance-loggers]
=== Creating instance loggers

Even though we recommend you to <<class-loggers,create class loggers>>, there might be occasions (most notably while {logging-services-url}/log4j/2.x/manual/webapp.html#log-separation[sharing classes in Jakarta EE environments]) necessitating loggers associated with each instance.
You can achieve this as follows:

[#create-instance-logger]
==== Creating a logger in the class

This is the traditional approach to create instance loggers.
It also happens to be the most efficient one, since the logger lookup is performed once and its result is stored in the instance field.

[source,kotlin]
----
import org.apache.logging.log4j.kotlin.logger

class DbTableService {

  private val logger = logger() // <1>

  fun truncateTable(tableName: String) {
    logger.warn { "truncating table `${tableName}`" }
    db.truncate(tableName)
  }

}
----
<1> Create a `Logger` associated with the class instance

[#extend-instance]
==== Extending the class from `Logging`

`Logging` interface contains a `logger` getter that you can use by extending the class from `Logging`:

[source,kotlin]
----
import org.apache.logging.log4j.kotlin.Logging

class DbTableService: Logging { // <1>

  fun truncateTable(tableName: String) {
    logger.warn { "truncating table `${tableName}`" }
    db.truncate(tableName)
  }

}
----
<1> Extending the class from `Logging` effectively creates a single `Logger` instance
. Assigned to the `logger` field
. Exclusively associated with the class instance (i.e., not shared among instances!)

[NOTE]
====
This getter-based approach incurs an extra overhead (compared to <<create-instance-logger>>) due to the logger lookup involved at runtime.
====

[#logger-extension]
==== Using `logger` extension property

You can use the `logger`  extension property to dynamically inject a logger at the spot:

[source,kotlin]
----
import org.apache.logging.log4j.kotlin.logger

class DbTableService {

  fun truncateTable(tableName: String) {
    logger.warn { "truncating table `${tableName}`" } // <1>
    db.truncate(tableName)
  }

}
----
<1> `logger` will look up the associated `Logger` instance for the encapsulating class

[NOTE]
====
This getter-based approach incurs an extra overhead (compared to <<create-instance-logger>>) due to the logger lookup involved at runtime.
====

[#thread-context]
== Thread context

The `ThreadContext` API has two facade objects provided: `ContextMap` and `ContextStack`.

[source,kotlin]
----
import org.apache.logging.log4j.kotlin.ContextMap
import org.apache.logging.log4j.kotlin.ContextStack

ContextMap["key"] = "value"
assert(ContextMap["key"] == "value")
assert("key" in ContextMap)

ContextMap += "anotherKey" to "anotherValue"
ContextMap -= "key"

ContextStack.push("message")
assert(!ContextStack.empty)
assert(ContextStack.depth == 1)
val message = ContextStack.peek()
assert(message == ContextStack.pop())
assert(ContextStack.empty)
----

A `CoroutineThreadContext` context element is provided to integrate logging context with coroutines.

We provide convenience functions `loggingContext` and `additionalLoggingContext` to create instances of `CoroutineThreadContext` with the appropriate context data.
The result of these functions can be passed directly to coroutine builders to set the context for the coroutine.

To set the context, ignoring any context currently in scope:

[source,kotlin]
----
launch(loggingContext(mapOf("myKey" to "myValue"), listOf("test"))) {
  assertEquals("myValue", ContextMap["myKey"])
  assertEquals("test", ContextStack.peek())
}
----

Or to preserve the existing context and add additional logging context:

[source,kotlin]
----
launch(additionalLoggingContext(mapOf("myKey" to "myValue"), listOf("test"))) {
  assertEquals("myValue", ContextMap["myKey"])
  assertEquals("test", ContextStack.peek())
}
----

Alternatively, to change the context without launching a new coroutine, the `withLoggingContext` and `withAdditionalLoggingContext` functions are provided:

[source,kotlin]
----
withAdditionalLoggingContext(mapOf("myKey" to "myValue"), listOf("test")) {
  assertEquals("myValue", ContextMap["myKey"])
  assertEquals("test", ContextStack.peek())
}
----

These functions are shorthand for `withContext(loggingContext(...))` or `withContext(additionalLoggingContext(...))`.

[#params]
== Parameter substitution

Unlike Java, Kotlin provides native functionality for https://kotlinlang.org/docs/reference/basic-syntax.html#using-string-templates[string templates].
However, using a string template still incurs the message construction cost if the logger level is not enabled.
To avoid this, prefer passing a lambda which won't be evaluated until necessary:

[source,kotlin]
----
logger.debug { "Logging in user ${user.name} with birthday ${user.calcBirthday()}" }
----

[#logger-names]
== Logger names

Most logging implementations use a hierarchical scheme for matching logger names with logging configuration.

In this scheme the logger name hierarchy is represented by `.` (dot) characters in the logger name, in a fashion very similar to the hierarchy used for Java/Kotlin package names.
The `Logger` property added by the `Logging` interface follows this convention: the interface ensures the `Logger` is automatically named according to the class it is being used in.

The value returned when calling the `logger()` extension method depends on the receiver of the extension.
When called within an object, the receiver is `this` and therefore the logger will again be named according to the class it is being used in.
However, a logger named via another class can be obtained as well:

[source,kotlin]
----
import org.apache.logging.log4j.kotlin

class MyClass: BaseClass {

  val logger = SomeOtherClass.logger()

  // ...

}
----

[#explicitly-named-loggers]
=== Explicitly Named Loggers

An explicitly-named logger may be obtained via the `logger` function that takes a `name` parameter:

[source,kotlin]
----
import org.apache.logging.log4j.kotlin

class MyClass: BaseClass {

  val logger = logger("MyCustomLoggerName")

  // ...

}
----

This is also needed in scopes that do not have a `this` object, such as top-level functions.
