staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/kotlin


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 13598
# - Commit ID: 4601fdec3a586abf14deec1fc1af563c5a32f126
# - Timestamp: 2026-04-01T11:35:39Z
