staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/kotlin


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 25764
# - Commit ID: f60ddbfa3c84ecf672436c3f6884cd40bc15aef1
# - Timestamp: 2024-06-20T07:42:08Z
