staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/kotlin


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 3653
# - Commit ID: 997d6078d5a2c752a100f6fe56c27a5070ad7e3c
# - Timestamp: 2026-04-01T14:11:08Z
