staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/kotlin


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 22792
# - Commit ID: 6fbb4e52803f0d1fec38572d9db63caa4736796b
# - Timestamp: 2026-03-31T15:03:05Z
